---
apiVersion: v1
kind: PersistentVolume
metadata:
 name: eazyschool-db-pv
 labels: 
  name: eazyschool-db-pv
spec:
 capacity:
  storage: 4Gi
 accessModes:
 - ReadWriteOnce
 persistentVolumeReclaimPolicy: Retain
 storageClassName: local-storage
 hostPath:
  path: /opt/mysql
...